CREATE TABLE STARTING_GRID
(
  SG_ID   INTEGER(10),
  STREET  INTEGER,
  NAME    VARCHAR(255),

  PRIMARY KEY (SG_ID)
);

CREATE TABLE STREET
(
  S_ID          INTEGER(10),
  S_LENGTH      INTEGER(10),
  STARTINGGRID  INTEGER(10),

  PRIMARY KEY (S_ID),
  FOREIGN KEY (STARTINGGRID) REFERENCES STARTING_GRID (SG_ID)
);


CREATE TABLE LANE
(
  L_ID   INTEGER(10),
  STREET INTEGER(10),

  PRIMARY KEY (L_ID),
  FOREIGN KEY (STREET) REFERENCES STREET (S_ID)
);


CREATE TABLE CONSRTUCTIONSITE
(
  CS_ID        INTEGER(10),
  CS_LENGTH    INTEGER(10),

  PRIMARY KEY (CS_ID),


);

CREATE TABLE STREET_SIGN (

  SS_ID         INTEGER(10),
  SPEED_LIMIT   INTEGER,

  PRIMARY KEY (SS_ID)
  FOREIGN KEY(SS_ID) REFERENCES STREET (S_ID)
);
 

CREATE TABLE CELL
(
  C_INDEX                     INTEGER(10),
  LANE                        INTEGER(10),
  BLOCKING_VEHICLE            INTEGER(10),
  BLOCKING_CONSTRUCTIONSITE   INTEGER(10),

  PRIMARY KEY (C_INDEX),
  FOREIGN KEY (LANE) REFERENCES LANE (L_ID),
  FOREIGN KEY (BLOCKING_VEHICLE) REFERENCES CONSRTUCTIONSITE (CS_ID),
  FOREIGN KEY (BLOCKING_CONSTRUCTIONSITE) REFERENCES CONSRTUCTIONSITE (CS_ID)
);


CREATE TABLE VEHICLE
(
  V_ID            INTEGER(10),
  STARTING_GRID   INTEGER(10),
  V_LENGTH        INTEGER(10),
  CURRENTSPEED    INTEGER(10),
  MAXSPEED        INTEGER(10),
  V_TYPE        VARCHAR(255),

  PRIMARY KEY (V_ID),
  FOREIGN KEY (STARTING_GRID) REFERENCES STARTING_GRID (SG_ID)

);

